# Chapter Content Validator Configuration
# This file defines validation rules for the MCP Deep Dive chapter

validation:
  # List of experiments in this chapter
  experiments:
    - experiments/01-protocol-inspector
    - experiments/02-mcp-server
    - experiments/03-mcp-client
    - experiments/04-security-lab

  # Prerequisites for this chapter
  prerequisites:
    - TypeScript basics
    - Node.js and npm
    - "Reading: concepts/mcp-basics.md"
    - "Reading: concepts/json-rpc.md"

  # Scenarios for validation testing
  scenarios:
    # Simple scenario: Basic tool implementation
    simple:
      type: tool
      description: "Implement a file batch rename MCP Server"
      requirements:
        - "Server starts successfully on stdio transport"
        - "tools/list returns a 'batch_rename' tool"
        - "Tool accepts file path list and rename pattern"
        - "Returns success/failure status for each file"
        - "Handles errors (file not found, permission denied)"
      verify: |
        The Learner Agent should be able to:
        1. Create a new MCP Server project
        2. Register a 'batch_rename' tool with proper Zod schema
        3. Implement the rename logic with error handling
        4. Test with MCP Inspector

    # Complex scenario: External API integration
    complex:
      type: integration
      description: "Implement a GitHub Issues MCP Server"
      requirements:
        - "Server connects to GitHub API"
        - "Implements 'list_issues' tool (repo owner/name -> issues)"
        - "Implements 'create_issue' tool (title, body -> new issue)"
        - "Implements 'add_comment' tool (issue number, comment -> posted)"
        - "Handles GitHub authentication (token)"
        - "Handles API errors and rate limiting"
      verify: |
        The Learner Agent should be able to:
        1. Set up GitHub API authentication
        2. Implement API calling logic
        3. Define proper Zod schemas for GitHub API responses
        4. Handle pagination for issue lists
        5. Provide clear error messages for API failures

# Knowledge checkpoints
# These are specific concepts the Learner must demonstrate understanding
knowledge_checkpoints:
  - checkpoint: "MCP Protocol Basics"
    indicators:
      - "Can explain initialize -> initialized handshake"
      - "Knows why console.log breaks stdio transport"
      - "Understands JSON-RPC message format"

  - checkpoint: "Tool Implementation"
    indicators:
      - "Can define Zod schema for tool input"
      - "Knows how to register tool handlers"
      - "Returns proper content array format"

  - checkpoint: "Error Handling"
    indicators:
      - "Validates input with Zod before processing"
      - "Returns structured error responses"
      - "Uses console.error for logging"

# Common gaps to watch for
# This helps the Author Agent categorize and prioritize fixes
common_gaps:
  - category: "concept_missing"
    examples:
      - "JSON-RPC framing not explained"
      - "stdio vs HTTP transport differences unclear"
      - "Zod schema usage not demonstrated"

  - category: "step_unclear"
    examples:
      - "How to run the experiment not specified"
      - "Expected output not shown"
      - "Dependencies not listed"

  - category: "code_error"
    examples:
      - "Import paths incorrect"
      - "Type definitions missing"
      - "Example code has syntax errors"

  - category: "context_missing"
    examples:
      - "Why we do this step not explained"
      - "Connection to other experiments unclear"
      - "Real-world application not shown"
